---
- name: Assert that prerequisites exist
  tags: percona-release
  assert:
    that:
      - percona_pkg is defined
      - percona_ver is defined
      - percona_rel is defined
      - percona_baseurl is defined

- name: Generate random package name
  tags: percona-release
  command: mktemp -u --suffix .rpm
  register: percona_mktemp

- name: Fetch {{ percona_pkg }} to temporary destination
  tags: percona-release
  get_url:
    url: "{{ percona_fetch }}"
    dest: "{{ percona_mktemp.stdout }}"
  register: percona_get_url
  when: percona_mktemp|success

- name: Ensure that the {{ percona_pkg }} package is installed
  tags: percona-release
  yum:
    name: "{{ item }}"
    state: present
  register: percona_yum
  with_items: "{{ percona_mktemp.stdout }}"
  when: percona_get_url|success

- name: Applying {{ percona_pkg }} configurations
  tags: percona-release
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: percona-release.repo.j2, dst: /etc/yum.repos.d/percona-release.repo }
  when: percona_yum|success

- name: Prune temporary package from the filesystem
  tags: percona-release
  file:
    path: "{{ percona_mktemp.stdout }}"
    state: absent
  when:
    - percona_mktemp|success
    - percona_yum|success
...
